WebHashcat/API/urls.py
from django.conf.urls import url

from . import views

app_name = 'API'
urlpatterns = [
        url(r'^statistics$', views.api_statistics, name='api_statistics'),
        url(r'^cracked_ratio$', views.api_cracked_ratio, name='api_cracked_ratio'),
        url(r'^running_sessions$', views.api_running_sessions, name='api_running_sessions'),
        url(r'^error_sessions$', views.api_error_sessions, name='api_error_sessions'),
        url(r'^node_status$', views.api_node_status, name='api_node_status'),
        url(r'^hashfiles$', views.api_hashfiles, name='api_hashfiles'),
        url(r'^hashfile_sessions$', views.api_hashfile_sessions, name='api_hashfile_sessions'),
        url(r'^session_action$', views.api_session_action, name='api_session_action'),
        url(r'^hashfile_action$', views.api_hashfile_action, name='api_hashfile_action'),
        url(r'^hashfile_cracked/(.*)$', views.api_hashfile_cracked, name='api_hashfile_cracked'),
        url(r'^hashfile_top_password/(.*)/(.*)$', views.api_hashfile_top_password, name='api_hashfile_top_password'),
        url(r'^hashfile_top_password_len/(.*)/(.*)$', views.api_hashfile_top_password_len, name='api_hashfile_top_password_len'),
        url(r'^hashfile_top_password_charset/(.*)/(.*)$', views.api_hashfile_top_password_charset, name='api_hashfile_top_password_charset'),
        url(r'^get_messages$', views.api_get_messages, name='api_get_messages'),
        url(r'^search_list$', views.api_search_list, name='api_search_list'),
        url(r'^search_action$', views.api_search_action, name='api_search_action'),
]

WebHashcat/Nodes/urls.py
from django.conf.urls import url

from . import views

app_name = 'Nodes'
urlpatterns = [
        url(r'^nodes$', views.nodes, name='nodes'),
        url(r'^node/(.*)$', views.node, name='node'),
        url(r'^new_node$', views.new_node, name='new_node'),
        url(r'^delete_node/(.*)$', views.delete_node, name='delete_node'),
]

WebHashcat/Nodes/models.py
from django.db import models

# Create your models here.

class Node(models.Model):
    name = models.CharField(max_length=30)
    hostname = models.CharField(max_length=15)
    port = models.IntegerField()
    username = models.CharField(max_length=30)
    password = models.CharField(max_length=30)

WebHashcat/Nodes/views.py
import json
import csv
import random
import string
import os.path
import tempfile
import humanize
import time
import requests
from collections import OrderedDict

from django.shortcuts import render
from django.shortcuts import redirect
from django.template import loader
from django.urls import reverse
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.middleware.csrf import get_token
from django.db.models import Q, Count, BinaryField
from django.db.models.functions import Cast
from django.db import connection
from django.contrib import messages

from django.shortcuts import get_object_or_404

from operator import itemgetter

from .models import Node

from Utils.hashcatAPI import HashcatAPI
from Utils.hashcat import Hashcat

# Create your views here.

@login_required
def nodes(request, error_msg=""):

    context = {}
    context["Section"] = "Nodes"

    if len(error_msg) != 0:
        context["error_message"] = error_msg

    context["node_list"] = Node.objects.all()

    template = loader.get_template('Nodes/nodes.html')
    return HttpResponse(template.render(context, request))

@login_required
def node(request, node_name, error_msg=""):

    context = {}
    context["Section"] = "Nodes"

    if len(error_msg) != 0:
        context["error_message"] = error_msg

        template = loader.get_template('Nodes/node.html')
        return HttpResponse(template.render(context, request))

    node_item = get_object_or_404(Node, name=node_name)

    context["node_name"] = node_item.name
    context["hostname"] = node_item.hostname
    context["port"] = node_item.port

    if request.method == 'POST':
        if request.POST["action"] == "synchronize":

            hashcat_api = HashcatAPI(node_item.hostname, node_item.port, node_item.username, node_item.password)
            node_data = hashcat_api.get_hashcat_info()

            rule_list = Hashcat.get_rules()
            mask_list = Hashcat.get_masks()
            wordlist_list = Hashcat.get_wordlists()

            for rule in rule_list:
                if not rule["name"] in node_data["rules"]:
                    hashcat_api.upload_rule(rule["name"], open(rule["path"], 'rb').read())
                elif node_data["rules"][rule["name"]]["md5"] != rule["md5"]:
                    hashcat_api.upload_rule(rule["name"], open(rule["path"], 'rb').read())

            for mask in mask_list:
                if not mask["name"] in node_data["masks"]:
                    hashcat_api.upload_mask(mask["name"], open(mask["path"], 'rb').read())
                elif node_data["masks"][mask["name"]]["md5"] != mask["md5"]:
                    hashcat_api.upload_mask(mask["name"], open(mask["path"], 'rb').read())

            for wordlist in wordlist_list:
                if not wordlist["name"] in node_data["wordlists"]:
                    hashcat_api.upload_wordlist(wordlist["name"], open(wordlist["path"], 'rb').read())
                elif node_data["wordlists"][wordlist["name"]]["md5"] != wordlist["md5"]:
                    hashcat_api.upload_wordlist(wordlist["name"], open(wordlist["path"], 'rb').read())

    try:
        hashcat_api = HashcatAPI(node_item.hostname, node_item.port, node_item.username, node_item.password)
        node_data = hashcat_api.get_hashcat_info()

        if node_data["response"] == "error":
            return node(request, node_name, error_msg=node_data["message"])
    except requests.exceptions.ConnectionError:
        return nodes(request, error_msg="Unable to connect to node %s at: %s:%d" % (node_item.name, node_item.hostname, node_item.port))

    rule_list = Hashcat.get_rules()
    mask_list = Hashcat.get_masks()
    wordlist_list = Hashcat.get_wordlists()

    for rule in rule_list:
        if not rule["name"] in node_data["rules"]:
            rule["synchro"] = False
        elif node_data["rules"][rule["name"]]["md5"] != rule["md5"]:
            rule["synchro"] = False
        else:
            rule["synchro"] = True

    for mask in mask_list:
        if not mask["name"] in node_data["masks"]:
            mask["synchro"] = False
        elif node_data["masks"][mask["name"]]["md5"] != mask["md5"]:
            mask["synchro"] = False
        else:
            mask["synchro"] = True

    for wordlist in wordlist_list:
        if not wordlist["name"] in node_data["wordlists"]:
            wordlist["synchro"] = False
        elif node_data["wordlists"][wordlist["name"]]["md5"] != wordlist["md5"]:
            wordlist["synchro"] = False
        else:
            wordlist["synchro"] = True

    hash_type_list = sorted(node_data["hash_types"], key=itemgetter('id'))

    context["version"] = node_data["version"]
    context["rule_list"] = rule_list
    context["mask_list"] = mask_list
    context["wordlist_list"] = wordlist_list
    context["hash_type_list"] = hash_type_list

    template = loader.get_template('Nodes/node.html')
    return HttpResponse(template.render(context, request))


@login_required
def new_node(request):
    if request.method == 'POST':
        node_name = request.POST["name"]
        hostname = request.POST["hostname"]
        port = request.POST["port"]
        username = request.POST["username"]
        password = request.POST["password"]

        try:
            port = int(port)
        except ValueError:
            port = -1

        if port > 0 and port < 65636:
            Node.objects.update_or_create(name=node_name,
                    defaults={
                        'name': node_name,
                        'hostname': hostname,
                        'port': port,
                        'username': username,
                        'password': password,
                        }
            )
        return redirect('Nodes:nodes')

@login_required
def delete_node(request, node_name):

    try:
        obj = Node.objects.get(name=node_name)
        obj.delete()
    except Node.DoesNotExist:
        pass

    return redirect('Nodes:nodes')

WebHashcat/Nodes/templates/Nodes/node.html
{% extends "base.html" %}

{% block content %}
   <div class="row">
      <div class="col-md-6">

         <div class="panel panel-success">
            <div class="panel-heading">

         <div style="float: right;">
            <form method="post">
               {% csrf_token %}
               <input type="hidden" name="action" value="synchronize"></input>
               <button type="submit" class="btn btn-primary btn-xs confirm"><span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>Synchronize</button>
            </form>
         </div>

               <h2 class="panel-title">{{ node_name }}</h2>

            </div>
            <div class="panel-body">
               Hostname: {{ hostname }}<br/>
               Port: {{ port }}<br/>
               Hashcat version: {{ version }}<br/>
            </div>
         </div>

         <h3> Rules </h3>
         <table class="table table-striped table-condensed">
            <tr>
               <td><b>Name</b></td>
               <td><b>MD5</b></td>
               <td></td>
            </tr>
            {% for rule in rule_list %}
            <tr>
               <td>{{ rule.name }}</td>
               <td>{{ rule.md5 }}</td>
               <td>{% if rule.synchro %}<span class="glyphicon glyphicon-ok" style="color: green; float: right"></span>{% else %}<span class="glyphicon glyphicon-remove" style="color: red; float: right"></span>{% endif %}</td>
            </tr>
            {% endfor %}
         </table>

         <h3> Masks </h3>
         <table class="table table-striped table-condensed">
            <tr>
               <td><b>Name</b></td>
               <td><b>MD5</b></td>
               <td></td>
            </tr>
            {% for mask in mask_list %}
            <tr>
               <td>{{ mask.name }}</td>
               <td>{{ mask.md5 }}</td>
               <td>{% if mask.synchro %}<span class="glyphicon glyphicon-ok" style="color: green; float: right"></span>{% else %}<span class="glyphicon glyphicon-remove" style="color: red; float: right"></span>{% endif %}</td>
            </tr>
            {% endfor %}
         </table>

         <h3> Wordlists </h3>
         <table class="table table-striped table-condensed">
            <tr>
               <td><b>Name</b></td>
               <td><b>MD5</b></td>
               <td></td>
            </tr>
            {% for wordlist in wordlist_list %}
            <tr>
               <td>{{ wordlist.name }}</td>
               <td>{{ wordlist.md5 }}</td>
               <td>{% if wordlist.synchro %}<span class="glyphicon glyphicon-ok" style="color: green; float: right"></span>{% else %}<span class="glyphicon glyphicon-remove" style="color: red; float: right"></span>{% endif %}</td>
            </tr>
            {% endfor %}
         </table>

      </div>
      <div class="col-md-6">


         <h3> Hash Types</h3> 
         <table class="table table-striped table-condensed">
            <tr>
               <td><b>id</b></td>
               <td><b>Name</b></td>
               <td><b>Description</b></td>
            </tr>
            {% for hash_type in hash_type_list %}
            <tr>
               <td>{{ hash_type.id }}</td>
               <td>{{ hash_type.name }}</td>
               <td>{{ hash_type.description }}</td>
            </tr>
            {% endfor %}
         </table>

      </div>
   </div>

{% endblock %}

WebHashcat/Nodes/templates/Nodes/nodes.html
{% extends "base.html" %}

{% block content %}
   <h1> Nodes </h1> {{ node_list|length }} nodes

   <table class="table table-striped table-condensed">
      <tr>
         <td><b>Node</b></td>
         <td><b>IP</b></td>
         <td><b>Port</b></td>
         <td></td>
      </tr>
      {% for node in node_list %}
      <tr>
         <td><a href="{% url "Nodes:node" node.name %}">{{ node.name }}</a></td>
         <td>{{ node.hostname }}</td>
         <td>{{ node.port }}</td>
         <td><a href="{% url "Nodes:delete_node" node.name %}"><button type="button" class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span>Remove</button><a/></td>
      </tr>
      {% endfor %}
   </table>

   </br>
   <button type="button" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#action_new">New</button></td>

   <!-- Modal -->
   <div class="modal fade" id="action_new" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
     <div class="modal-dialog" role="document">
       <div class="modal-content">
         <div class="modal-header">
           <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
           <h4 class="modal-title" id="myModalLabel">New node</h4>
         </div>

         <form action="{% url "Nodes:new_node" %}" enctype="multipart/form-data" method="post">
            {% csrf_token %}

            <div class="modal-body">
                  <label for="name">Name</label>
                  <input type="text" class="form-control" id="name" name="name">
                  </br>
                  <label for="hostname">Hostname</label>
                  <input type="text" class="form-control" id="hostname" name="hostname">
                  </br>
                  <label for="port">Port</label>
                  <input type="number" class="form-control" id="port" name="port">
                  </br>
                  <label for="username">Username</label>
                  <input type="text" class="form-control" id="username" name="username">
                  </br>
                  <label for="password">Password</label>
                  <input type="text" class="form-control" id="password" name="password">
            </div>

            <div class="modal-footer">
               <button type="submit" class="btn btn-primary" >New</button>
            </div>
         </form>

       </div>
     </div>
   </div>

{% endblock %}