WebHashcat/API/urls.py
from django.conf.urls import url

from . import views

app_name = 'API'
urlpatterns = [
        url(r'^statistics$', views.api_statistics, name='api_statistics'),
        url(r'^cracked_ratio$', views.api_cracked_ratio, name='api_cracked_ratio'),
        url(r'^running_sessions$', views.api_running_sessions, name='api_running_sessions'),
        url(r'^error_sessions$', views.api_error_sessions, name='api_error_sessions'),
        url(r'^node_status$', views.api_node_status, name='api_node_status'),
        url(r'^hashfiles$', views.api_hashfiles, name='api_hashfiles'),
        url(r'^hashfile_sessions$', views.api_hashfile_sessions, name='api_hashfile_sessions'),
        url(r'^session_action$', views.api_session_action, name='api_session_action'),
        url(r'^hashfile_action$', views.api_hashfile_action, name='api_hashfile_action'),
        url(r'^hashfile_cracked/(.*)$', views.api_hashfile_cracked, name='api_hashfile_cracked'),
        url(r'^hashfile_top_password/(.*)/(.*)$', views.api_hashfile_top_password, name='api_hashfile_top_password'),
        url(r'^hashfile_top_password_len/(.*)/(.*)$', views.api_hashfile_top_password_len, name='api_hashfile_top_password_len'),
        url(r'^hashfile_top_password_charset/(.*)/(.*)$', views.api_hashfile_top_password_charset, name='api_hashfile_top_password_charset'),
        url(r'^get_messages$', views.api_get_messages, name='api_get_messages'),
        url(r'^search_list$', views.api_search_list, name='api_search_list'),
        url(r'^search_action$', views.api_search_action, name='api_search_action'),
]

WebHashcat/Hashcat/urls.py
from django.conf.urls import url

from . import views

app_name = 'Hashcat'
urlpatterns = [
        url(r'^$', views.dashboard, name='index'),
        url(r'^hashfiles$', views.hashfiles, name='hashfiles'),
        url(r'^search$', views.search, name='search'),
        url(r'^files$', views.files, name='files'),
        url(r'^new_session$', views.new_session, name='new_session'),
        url(r'^upload_rule$', views.upload_rule, name='upload_rule'),
        url(r'^upload_mask$', views.upload_mask, name='upload_mask'),
        url(r'^upload_wordlist$', views.upload_wordlist, name='upload_wordlist'),
        url(r'^hashfile/(.*)$', views.hashfile, name='hashfile'),
        url(r'^file/cracked/(.*)$', views.export_cracked, name='export_cracked'),
        url(r'^file/uncracked/(.*)$', views.export_uncracked, name='export_uncracked'),
        url(r'^csv/masks/(.*)$', views.csv_masks, name='csv_masks'),
        url(r'^export_search/(.*)$', views.export_search, name='export_search'),
]

WebHashcat/Nodes/urls.py
from django.conf.urls import url

from . import views

app_name = 'Nodes'
urlpatterns = [
        url(r'^nodes$', views.nodes, name='nodes'),
        url(r'^node/(.*)$', views.node, name='node'),
        url(r'^new_node$', views.new_node, name='new_node'),
        url(r'^delete_node/(.*)$', views.delete_node, name='delete_node'),
]

WebHashcat/Hashcat/models.py
from django.db import models

from Nodes.models import Node

# Create your models here.

class Hashfile(models.Model):
    name = models.CharField(max_length=30)
    hashfile = models.CharField(max_length=30)
    hash_type = models.IntegerField()
    line_count = models.IntegerField()
    cracked_count = models.IntegerField(default=0)
    username_included = models.BooleanField()

class Session(models.Model):
    name = models.CharField(max_length=100)
    hashfile = models.ForeignKey(Hashfile, on_delete=models.CASCADE)
    node = models.ForeignKey(Node, on_delete=models.CASCADE)
    potfile_line_retrieved = models.IntegerField()

class Hash(models.Model):
    hashfile = models.ForeignKey(Hashfile, on_delete=models.CASCADE)
    hash_type = models.IntegerField()
    username = models.CharField(max_length=190, null=True)
    password = models.CharField(max_length=190, null=True)
    hash = models.TextField(max_length=4096, null=True) # Changed from char to text
    hash_hash = models.CharField(max_length=190, null=True) # sha1 of the hash for joins
    password_len = models.IntegerField(null=True)
    password_charset = models.CharField(max_length=100, null=True)
    password_mask = models.CharField(null=True, max_length=190)

    class Meta:
        indexes = [
            models.Index(fields=['hashfile'], name="hashfileid_index"),
            models.Index(fields=['hashfile', 'hash_hash'], name="hashfileid_hash_index"),
            models.Index(fields=['hash_hash', 'hash_type'], name="hash_index"),
        ]

class Search(models.Model):
    name = models.CharField(max_length=100)
    status = models.CharField(max_length=100)
    output_lines = models.IntegerField(null=True)
    output_file = models.TextField()
    processing_time = models.IntegerField(null=True)
    json_search_info = models.TextField()

WebHashcat/Hashcat/views.py
import json
import csv
import random
import string
import os.path
import tempfile
import humanize
import time
from datetime import datetime
from collections import OrderedDict

from django.shortcuts import render
from django.shortcuts import redirect
from django.template import loader
from django.urls import reverse
from django.http import HttpResponse
from django.http import StreamingHttpResponse
from django.http import FileResponse
from django.contrib.auth.decorators import login_required
from django.middleware.csrf import get_token
from django.db.models import Q, Count, BinaryField
from django.db.models.functions import Cast
from django.db import connection
from django.contrib import messages
from django.db.utils import OperationalError

from django.shortcuts import get_object_or_404

from operator import itemgetter

from Nodes.models import Node
from .models import Hashfile, Session, Hash, Search

from Utils.hashcatAPI import HashcatAPI
from Utils.hashcat import Hashcat
from Utils.utils import init_hashfile_locks
from Utils.utils import Echo
from Utils.tasks import import_hashfile_task, run_search_task
# Create your views here.

@login_required
def dashboard(request):
    context = {}
    context["Section"] = "Dashboard"

    template = loader.get_template('Hashcat/dashboard.html')
    return HttpResponse(template.render(context, request))

@login_required
def hashfiles(request):
    context = {}
    context["Section"] = "Hashes"

    if request.method == 'POST':
        if request.POST["action"] == "add":
            hash_type=int(request.POST["hash_type"])

            hashfile_name = ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(12)) + ".hashfile"
            hashfile_path = os.path.join(os.path.dirname(__file__), "..", "Files", "Hashfiles", hashfile_name)

            hashes = request.POST["hashes"]
            f = open(hashfile_path, 'w')
            if len(hashes) == 0 and "hashfile" in request.FILES:
                for chunk in request.FILES['hashfile'].chunks():
                    f.write(chunk.decode('UTF-8', 'backslashreplace'))
            else:
                f.write(hashes.strip())
            f.close()

            username_included = "username_included" in request.POST

            hashfile = Hashfile(
                name=request.POST['name'],
                hashfile=hashfile_name,
                hash_type=hash_type,
                line_count=0,
                cracked_count = 0,
                username_included=username_included,
            )
            hashfile.save()
            init_hashfile_locks(hashfile)

            # Update the new file with the potfile, this may take a while, but it is processed in a background task
            import_hashfile_task.delay(hashfile.id)

            if hash_type != -1: # if != plaintext
                messages.success(request, "Hashfile successfully added")
            else:
                messages.success(request, "Plaintext file successfully added")

    context["node_list"] = Node.objects.all()
    context["hash_type_list"] = [{'id': -1, 'name': 'Plaintext'}] + sorted(list(Hashcat.get_hash_types().values()), key=itemgetter('name'))
    context["rule_list"] = [{'name': None}] + sorted(Hashcat.get_rules(detailed=False), key=itemgetter('name'))
    context["mask_list"] = sorted(Hashcat.get_masks(detailed=False), key=itemgetter('name'))
    context["wordlist_list"] = sorted(Hashcat.get_wordlists(detailed=False), key=itemgetter('name'))

    template = loader.get_template('Hashcat/hashes.html')
    return HttpResponse(template.render(context, request))

@login_required
def search(request):
    context = {}
    context["Section"] = "Search"

    context["hashfile_list"] = Hashfile.objects.order_by('name')
    if request.method == 'POST':
        search_info = {}
        if len(request.POST["search_pattern"]) != 0:
            search_info["pattern"] = request.POST["search_pattern"]
        if "all_hashfiles" in request.POST:
            search_info["all_hashfiles"] = True
        else:
            search_info["hashfiles"] = request.POST.getlist("hashfile_search[]")
        if "ignore_uncracked" in request.POST:
            search_info["ignore_uncracked"] = True

        search_filename = ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(12)) + ".csv"
        output_file = os.path.join(os.path.dirname(__file__), "..", "Files", "Searches", search_filename)

        search = Search(
            name=request.POST['search_name'],
            status="Starting",
            output_lines=None,
            output_file=output_file,
            json_search_info=json.dumps(search_info),
        )
        search.save()

        run_search_task.delay(search.id)

    template = loader.get_template('Hashcat/search.html')
    return HttpResponse(template.render(context, request))

@login_required
def files(request):
    context = {}
    context["Section"] = "Files"

    if request.method == 'POST':
        if request.POST["action"] == "remove":
            if request.POST["filetype"] == "rule":
                Hashcat.remove_rule(request.POST["filename"])
            elif request.POST["filetype"] == "mask":
                Hashcat.remove_mask(request.POST["filename"])
            elif request.POST["filetype"] == "wordlist":
                Hashcat.remove_wordlist(request.POST["filename"])

    context["rule_list"] = Hashcat.get_rules()
    context["mask_list"] = Hashcat.get_masks()
    context["wordlist_list"] = Hashcat.get_wordlists()

    template = loader.get_template('Hashcat/files.html')
    return HttpResponse(template.render(context, request))

@login_required
def new_session(request):
    if request.method == 'POST':
        #session_name = request.POST["name"]

        node_name = request.POST["node"]
        node = get_object_or_404(Node, name=node_name)

        hashfile = get_object_or_404(Hashfile, id=request.POST['hashfile_id'])

        crack_type = request.POST["crack_type"]
        if crack_type == "dictionary":
            rule = request.POST["rule"] if request.POST["rule"] != "None" else None
            wordlist = request.POST["wordlist"]
        elif crack_type == "mask":
            mask = request.POST["mask"]

        device_type = int(request.POST["device_type"])

        if request.POST["end_datetime"]:
            end_timestamp = int(datetime.strptime(request.POST["end_datetime"], "%m/%d/%Y %I:%M %p").timestamp())
        else:
            end_timestamp = None

        session_name = ("%s-%s" % (hashfile.name, ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(12)))).replace(" ", "_")

        if "debug" in request.POST:
            hashcat_debug_file = True
        else:
            hashcat_debug_file = False

        hashcat_api = HashcatAPI(node.hostname, node.port, node.username, node.password)
        if crack_type == "dictionary":
            res = hashcat_api.create_dictionary_session(session_name, hashfile, rule, wordlist, device_type, end_timestamp, hashcat_debug_file)
        elif crack_type == "mask":
            res = hashcat_api.create_mask_session(session_name, hashfile, mask, device_type, end_timestamp, hashcat_debug_file)

        if res["response"] == "error":
            messages.error(request, res["message"])
            return redirect('Hashcat:hashfiles')

        messages.success(request, "Session successfully created")

        session = Session(
                name=session_name,
                hashfile=hashfile,
                node = node,
                potfile_line_retrieved=0,
        )
        session.save()

    return redirect('Hashcat:hashfiles')

@login_required
def upload_rule(request):
    if request.method == 'POST':
        name = request.POST["name"]

        if "file" in request.FILES:
            # get from file
            f = request.FILES["file"]
            rule_file = f.read()

            Hashcat.upload_rule(name, rule_file)

    return redirect('Hashcat:files')

@login_required
def upload_mask(request):
    if request.method == 'POST':
        name = request.POST["name"]

        if "file" in request.FILES:
            # get from file
            f = request.FILES["file"]
            mask_file = f.read()

            Hashcat.upload_mask(name, mask_file)


    return redirect('Hashcat:files')

@login_required
def upload_wordlist(request):
    if request.method == 'POST':
        name = request.POST["name"]

        if "file" in request.FILES:
            # get from file
            f = request.FILES["file"]
            wordlist_file = f.read()

            Hashcat.upload_wordlist(name, wordlist_file)

    return redirect('Hashcat:files')

@login_required
def hashfile(request, hashfile_id, error_msg=''):
    context = {}
    context["Section"] = "Hashfile"

    hashfile = get_object_or_404(Hashfile, id=hashfile_id)

    context['hashfile'] = hashfile
    context['lines'] = humanize.intcomma(hashfile.line_count)
    context['recovered'] = "%s (%.2f%%)" % (humanize.intcomma(hashfile.cracked_count), hashfile.cracked_count/hashfile.line_count*100) if hashfile.line_count != 0 else "0"
    context['hash_type'] = "Plaintext" if hashfile.hash_type == -1 else Hashcat.get_hash_types()[hashfile.hash_type]["name"]

    template = loader.get_template('Hashcat/hashfile.html')
    return HttpResponse(template.render(context, request))

@login_required
def export_cracked(request, hashfile_id):
    hashfile = get_object_or_404(Hashfile, id=hashfile_id)

    cracked_hashes = Hash.objects.filter(hashfile_id=hashfile.id, password__isnull=False)

    if hashfile.username_included:
        response = StreamingHttpResponse(("%s:%s\n" % (item.username, item.password) for item in cracked_hashes), content_type="text/txt")
    else:
        response = StreamingHttpResponse(("%s:%s\n" % (item.hash, item.password) for item in cracked_hashes), content_type="text/txt")

WebHashcat/Hashcat/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static "favicon.ico" %}">

    <title>WebHashcat</title>

    <!-- Libraries CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "css/dataTables.bootstrap.min.css" %}" rel="stylesheet">
    <link type="text/css" href="{% static "css/buttons.bootstrap.min.css" %}" rel="stylesheet" />
    <link type="text/css" href="{% static "css/bootstrap-datetimepicker.css" %}" rel="stylesheet" />
    <!-- Custom styles for this template -->
    <link href="{% static "css/dashboard.css" %}" rel="stylesheet">
    <link href="{% static "css/custom.css" %}" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static "js/jquery.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/jquery.dataTables.min.js" %}"></script>
    <script src="{% static "js/dataTables.bootstrap.min.js" %}"></script>
    <script src="{% static "js/dataTables.buttons.min.js" %}"></script>
    <script src="{% static "js/buttons.bootstrap.min.js" %}"></script>
    <script src="{% static "js/buttons.html5.min.js" %}"></script>
    <script src="{% static "js/canvasjs.min.js" %}"></script>
    <script src="{% static "js/jquery.canvasjs.min.js" %}"></script>
    <script src="{% static "js/jqueryFileTree.js" %}"></script>
    <script src="{% static "js/highcharts.js" %}"></script>
    <script src="{% static "js/exporting.js" %}"></script>
    <script src="{% static "js/moment.js" %}"></script>
    <script src="{% static "js/bootstrap-datetimepicker.js" %}"></script>


  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url "Hashcat:index" %}">WebHashcat</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            {% if Section == "Hashes" or Section == "Files" or Section == "Hashfile" %}
               <li class="active"><a href="{% url "Hashcat:hashfiles" %}">Hashcat</a></li>
            {% else %}
               <li ><a href="{% url "Hashcat:hashfiles" %}">Hashcat</a></li>
            {% endif %}
            {% if Section == "Nodes" %}
               <li class="active"><a href="{% url "Nodes:nodes" %}">Nodes</a></li>
            {% else %}
               <li ><a href="{% url "Nodes:nodes" %}">Nodes</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">

        {% if Section != "Dashboard" %}

        <div class="col-sm-3 col-md-2 sidebar">
          {% if Section == "Hashes" or Section == "Search" or Section == "Files" or Section == "Hashfile" %}
          <ul class="nav nav-sidebar">
            {% if Section == "Hashes" or Section == "Hashfile" %}
               <li class="active"><a href="{% url "Hashcat:hashfiles" %}">Hashfiles</a></li>
            {% else %}
               <li ><a href="{% url "Hashcat:hashfiles" %}">Hashfiles</a></li>
            {% endif %}
            <li {% if Section == "Search" %}class="active"{% endif %}><a href="{% url "Hashcat:search" %}">Search</a></li>
            {% if Section == "Files" %}
               <li class="active"><a href="{% url "Hashcat:files" %}">Files</a></li>
            {% else %}
               <li ><a href="{% url "Hashcat:files" %}">Files</a></li>
            {% endif %}
          {% endif %}
          {% if Section == "Nodes" %}
          <ul class="nav nav-sidebar">
            {% if Section == "Nodes" %}
               <li class="active"><a href="{% url "Nodes:nodes" %}">Nodes</a></li>
            {% else %}
               <li ><a href="{% url "Nodes:nodes" %}">Nodes</a></li>
            {% endif %}
          </ul> 
          {% endif %}
        </div>

        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        {% else %}
        <div class="col-md-12 main">
        {% endif %}

          {% if error_message %}
          </br>
          <div class="alert alert-danger" role="alert">{{ error_message }}</div>
          {% endif %}
          {% if messages %}
            {% for message in messages %}
               {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
               <div class="alert alert-danger alert-dismissable fade in">
                  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                  <strong>Error!</strong> {{ message }}
               </div>
               {% elif message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
               <div class="alert alert-warning alert-dismissable fade in">
                  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                  {{ message }}
               </div>
               {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
               <div class="alert alert-success alert-dismissable fade in">
                  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                  {{ message }}
               </div>
               {% else %}
               <div class="alert alert-info alert-dismissable fade in">
                  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                  {{ message }}
               </div>
               {% endif %}
            {% endfor %}
         {% endif %}


          {% block content %}
          <div class="starter-template">
              <h1>Bootstrap starter template</h1>
              <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
          </div>
          {% endblock %}

        </div>
      </div>
    </div>

  </body>
</html>