WebHashcat/API/urls.py
from django.conf.urls import url

from . import views

app_name = 'API'
urlpatterns = [
        url(r'^statistics$', views.api_statistics, name='api_statistics'),
        url(r'^cracked_ratio$', views.api_cracked_ratio, name='api_cracked_ratio'),
        url(r'^running_sessions$', views.api_running_sessions, name='api_running_sessions'),
        url(r'^error_sessions$', views.api_error_sessions, name='api_error_sessions'),
        url(r'^node_status$', views.api_node_status, name='api_node_status'),
        url(r'^hashfiles$', views.api_hashfiles, name='api_hashfiles'),
        url(r'^hashfile_sessions$', views.api_hashfile_sessions, name='api_hashfile_sessions'),
        url(r'^session_action$', views.api_session_action, name='api_session_action'),
        url(r'^hashfile_action$', views.api_hashfile_action, name='api_hashfile_action'),
        url(r'^hashfile_cracked/(.*)$', views.api_hashfile_cracked, name='api_hashfile_cracked'),
        url(r'^hashfile_top_password/(.*)/(.*)$', views.api_hashfile_top_password, name='api_hashfile_top_password'),
        url(r'^hashfile_top_password_len/(.*)/(.*)$', views.api_hashfile_top_password_len, name='api_hashfile_top_password_len'),
        url(r'^hashfile_top_password_charset/(.*)/(.*)$', views.api_hashfile_top_password_charset, name='api_hashfile_top_password_charset'),
        url(r'^get_messages$', views.api_get_messages, name='api_get_messages'),
        url(r'^search_list$', views.api_search_list, name='api_search_list'),
        url(r'^search_action$', views.api_search_action, name='api_search_action'),
]

WebHashcat/Hashcat/urls.py
from django.conf.urls import url

from . import views

app_name = 'Hashcat'
urlpatterns = [
        url(r'^$', views.dashboard, name='index'),
        url(r'^hashfiles$', views.hashfiles, name='hashfiles'),
        url(r'^search$', views.search, name='search'),
        url(r'^files$', views.files, name='files'),
        url(r'^new_session$', views.new_session, name='new_session'),
        url(r'^upload_rule$', views.upload_rule, name='upload_rule'),
        url(r'^upload_mask$', views.upload_mask, name='upload_mask'),
        url(r'^upload_wordlist$', views.upload_wordlist, name='upload_wordlist'),
        url(r'^hashfile/(.*)$', views.hashfile, name='hashfile'),
        url(r'^file/cracked/(.*)$', views.export_cracked, name='export_cracked'),
        url(r'^file/uncracked/(.*)$', views.export_uncracked, name='export_uncracked'),
        url(r'^csv/masks/(.*)$', views.csv_masks, name='csv_masks'),
        url(r'^export_search/(.*)$', views.export_search, name='export_search'),
]

WebHashcat/Hashcat/models.py
from django.db import models

from Nodes.models import Node

# Create your models here.

class Hashfile(models.Model):
    name = models.CharField(max_length=30)
    hashfile = models.CharField(max_length=30)
    hash_type = models.IntegerField()
    line_count = models.IntegerField()
    cracked_count = models.IntegerField(default=0)
    username_included = models.BooleanField()

class Session(models.Model):
    name = models.CharField(max_length=100)
    hashfile = models.ForeignKey(Hashfile, on_delete=models.CASCADE)
    node = models.ForeignKey(Node, on_delete=models.CASCADE)
    potfile_line_retrieved = models.IntegerField()

class Hash(models.Model):
    hashfile = models.ForeignKey(Hashfile, on_delete=models.CASCADE)
    hash_type = models.IntegerField()
    username = models.CharField(max_length=190, null=True)
    password = models.CharField(max_length=190, null=True)
    hash = models.TextField(max_length=4096, null=True) # Changed from char to text
    hash_hash = models.CharField(max_length=190, null=True) # sha1 of the hash for joins
    password_len = models.IntegerField(null=True)
    password_charset = models.CharField(max_length=100, null=True)
    password_mask = models.CharField(null=True, max_length=190)

    class Meta:
        indexes = [
            models.Index(fields=['hashfile'], name="hashfileid_index"),
            models.Index(fields=['hashfile', 'hash_hash'], name="hashfileid_hash_index"),
            models.Index(fields=['hash_hash', 'hash_type'], name="hash_index"),
        ]

class Search(models.Model):
    name = models.CharField(max_length=100)
    status = models.CharField(max_length=100)
    output_lines = models.IntegerField(null=True)
    output_file = models.TextField()
    processing_time = models.IntegerField(null=True)
    json_search_info = models.TextField()

WebHashcat/Hashcat/views.py
import json
import csv
import random
import string
import os.path
import tempfile
import humanize
import time
from datetime import datetime
from collections import OrderedDict

from django.shortcuts import render
from django.shortcuts import redirect
from django.template import loader
from django.urls import reverse
from django.http import HttpResponse
from django.http import StreamingHttpResponse
from django.http import FileResponse
from django.contrib.auth.decorators import login_required
from django.middleware.csrf import get_token
from django.db.models import Q, Count, BinaryField
from django.db.models.functions import Cast
from django.db import connection
from django.contrib import messages
from django.db.utils import OperationalError

from django.shortcuts import get_object_or_404

from operator import itemgetter

from Nodes.models import Node
from .models import Hashfile, Session, Hash, Search

from Utils.hashcatAPI import HashcatAPI
from Utils.hashcat import Hashcat
from Utils.utils import init_hashfile_locks
from Utils.utils import Echo
from Utils.tasks import import_hashfile_task, run_search_task
# Create your views here.

@login_required
def dashboard(request):
    context = {}
    context["Section"] = "Dashboard"

    template = loader.get_template('Hashcat/dashboard.html')
    return HttpResponse(template.render(context, request))

@login_required
def hashfiles(request):
    context = {}
    context["Section"] = "Hashes"

    if request.method == 'POST':
        if request.POST["action"] == "add":
            hash_type=int(request.POST["hash_type"])

            hashfile_name = ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(12)) + ".hashfile"
            hashfile_path = os.path.join(os.path.dirname(__file__), "..", "Files", "Hashfiles", hashfile_name)

            hashes = request.POST["hashes"]
            f = open(hashfile_path, 'w')
            if len(hashes) == 0 and "hashfile" in request.FILES:
                for chunk in request.FILES['hashfile'].chunks():
                    f.write(chunk.decode('UTF-8', 'backslashreplace'))
            else:
                f.write(hashes.strip())
            f.close()

            username_included = "username_included" in request.POST

            hashfile = Hashfile(
                name=request.POST['name'],
                hashfile=hashfile_name,
                hash_type=hash_type,
                line_count=0,
                cracked_count = 0,
                username_included=username_included,
            )
            hashfile.save()
            init_hashfile_locks(hashfile)

            # Update the new file with the potfile, this may take a while, but it is processed in a background task
            import_hashfile_task.delay(hashfile.id)

            if hash_type != -1: # if != plaintext
                messages.success(request, "Hashfile successfully added")
            else:
                messages.success(request, "Plaintext file successfully added")

    context["node_list"] = Node.objects.all()
    context["hash_type_list"] = [{'id': -1, 'name': 'Plaintext'}] + sorted(list(Hashcat.get_hash_types().values()), key=itemgetter('name'))
    context["rule_list"] = [{'name': None}] + sorted(Hashcat.get_rules(detailed=False), key=itemgetter('name'))
    context["mask_list"] = sorted(Hashcat.get_masks(detailed=False), key=itemgetter('name'))
    context["wordlist_list"] = sorted(Hashcat.get_wordlists(detailed=False), key=itemgetter('name'))

    template = loader.get_template('Hashcat/hashes.html')
    return HttpResponse(template.render(context, request))

@login_required
def search(request):
    context = {}
    context["Section"] = "Search"

    context["hashfile_list"] = Hashfile.objects.order_by('name')
    if request.method == 'POST':
        search_info = {}
        if len(request.POST["search_pattern"]) != 0:
            search_info["pattern"] = request.POST["search_pattern"]
        if "all_hashfiles" in request.POST:
            search_info["all_hashfiles"] = True
        else:
            search_info["hashfiles"] = request.POST.getlist("hashfile_search[]")
        if "ignore_uncracked" in request.POST:
            search_info["ignore_uncracked"] = True

        search_filename = ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(12)) + ".csv"
        output_file = os.path.join(os.path.dirname(__file__), "..", "Files", "Searches", search_filename)

        search = Search(
            name=request.POST['search_name'],
            status="Starting",
            output_lines=None,
            output_file=output_file,
            json_search_info=json.dumps(search_info),
        )
        search.save()

        run_search_task.delay(search.id)

    template = loader.get_template('Hashcat/search.html')
    return HttpResponse(template.render(context, request))

@login_required
def files(request):
    context = {}
    context["Section"] = "Files"

    if request.method == 'POST':
        if request.POST["action"] == "remove":
            if request.POST["filetype"] == "rule":
                Hashcat.remove_rule(request.POST["filename"])
            elif request.POST["filetype"] == "mask":
                Hashcat.remove_mask(request.POST["filename"])
            elif request.POST["filetype"] == "wordlist":
                Hashcat.remove_wordlist(request.POST["filename"])

    context["rule_list"] = Hashcat.get_rules()
    context["mask_list"] = Hashcat.get_masks()
    context["wordlist_list"] = Hashcat.get_wordlists()

    template = loader.get_template('Hashcat/files.html')
    return HttpResponse(template.render(context, request))

@login_required
def new_session(request):
    if request.method == 'POST':
        #session_name = request.POST["name"]

        node_name = request.POST["node"]
        node = get_object_or_404(Node, name=node_name)

        hashfile = get_object_or_404(Hashfile, id=request.POST['hashfile_id'])

        crack_type = request.POST["crack_type"]
        if crack_type == "dictionary":
            rule = request.POST["rule"] if request.POST["rule"] != "None" else None
            wordlist = request.POST["wordlist"]
        elif crack_type == "mask":
            mask = request.POST["mask"]

        device_type = int(request.POST["device_type"])

        if request.POST["end_datetime"]:
            end_timestamp = int(datetime.strptime(request.POST["end_datetime"], "%m/%d/%Y %I:%M %p").timestamp())
        else:
            end_timestamp = None

        session_name = ("%s-%s" % (hashfile.name, ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(12)))).replace(" ", "_")

        if "debug" in request.POST:
            hashcat_debug_file = True
        else:
            hashcat_debug_file = False

        hashcat_api = HashcatAPI(node.hostname, node.port, node.username, node.password)
        if crack_type == "dictionary":
            res = hashcat_api.create_dictionary_session(session_name, hashfile, rule, wordlist, device_type, end_timestamp, hashcat_debug_file)
        elif crack_type == "mask":
            res = hashcat_api.create_mask_session(session_name, hashfile, mask, device_type, end_timestamp, hashcat_debug_file)

        if res["response"] == "error":
            messages.error(request, res["message"])
            return redirect('Hashcat:hashfiles')

        messages.success(request, "Session successfully created")

        session = Session(
                name=session_name,
                hashfile=hashfile,
                node = node,
                potfile_line_retrieved=0,
        )
        session.save()

    return redirect('Hashcat:hashfiles')

@login_required
def upload_rule(request):
    if request.method == 'POST':
        name = request.POST["name"]

        if "file" in request.FILES:
            # get from file
            f = request.FILES["file"]
            rule_file = f.read()

            Hashcat.upload_rule(name, rule_file)

    return redirect('Hashcat:files')

@login_required
def upload_mask(request):
    if request.method == 'POST':
        name = request.POST["name"]

        if "file" in request.FILES:
            # get from file
            f = request.FILES["file"]
            mask_file = f.read()

            Hashcat.upload_mask(name, mask_file)


    return redirect('Hashcat:files')

@login_required
def upload_wordlist(request):
    if request.method == 'POST':
        name = request.POST["name"]

        if "file" in request.FILES:
            # get from file
            f = request.FILES["file"]
            wordlist_file = f.read()

            Hashcat.upload_wordlist(name, wordlist_file)

    return redirect('Hashcat:files')

@login_required
def hashfile(request, hashfile_id, error_msg=''):
    context = {}
    context["Section"] = "Hashfile"

    hashfile = get_object_or_404(Hashfile, id=hashfile_id)

    context['hashfile'] = hashfile
    context['lines'] = humanize.intcomma(hashfile.line_count)
    context['recovered'] = "%s (%.2f%%)" % (humanize.intcomma(hashfile.cracked_count), hashfile.cracked_count/hashfile.line_count*100) if hashfile.line_count != 0 else "0"
    context['hash_type'] = "Plaintext" if hashfile.hash_type == -1 else Hashcat.get_hash_types()[hashfile.hash_type]["name"]

    template = loader.get_template('Hashcat/hashfile.html')
    return HttpResponse(template.render(context, request))

@login_required
def export_cracked(request, hashfile_id):
    hashfile = get_object_or_404(Hashfile, id=hashfile_id)

    cracked_hashes = Hash.objects.filter(hashfile_id=hashfile.id, password__isnull=False)

    if hashfile.username_included:
        response = StreamingHttpResponse(("%s:%s\n" % (item.username, item.password) for item in cracked_hashes), content_type="text/txt")
    else:
        response = StreamingHttpResponse(("%s:%s\n" % (item.hash, item.password) for item in cracked_hashes), content_type="text/txt")

WebHashcat/Hashcat/templates/Hashcat/files.html
{% extends "base.html" %}

{% block content %}
   <div class="row">
      <div class="col-md-6">

         <div class="panel panel-primary">
            <div class="panel-heading">
               <div style="float: right;">
                  <button type="button" class="btn btn-xs btn-success" data-toggle="modal" data-target="#upload_rule">Upload</button>
               </div>
               <h2 class="panel-title">Rules</h2>
            </div>
            <div class="panel-body">

         <table class="panel-body table table-striped table-condensed">
            <tr>
               <td><b>Name</b></td>
               <td><b>MD5</b></td>
               <td></td>
            </tr>
            {% for rule in rule_list %}
            <tr>
               <td>{{ rule.name }}</td>
               <td>{{ rule.md5 }}</td>
               <td>
                     <form method="post">
                        {% csrf_token %}
                        <input type="hidden" name="action" value="remove"></input>
                        <input type="hidden" name="filetype" value="rule"></input>
                        <input type="hidden" name="filename" value="{{ rule.name }}"></input>
                        <button type="submit" class="btn btn-danger btn-xs confirm"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
                     </form>
               </td>
                     
            </tr>
            {% endfor %}
         </table>

            </div>
         </div>

         <div class="panel panel-primary">
            <div class="panel-heading">
               <div style="float: right;">
                  <button type="button" class="btn btn-xs btn-success" data-toggle="modal" data-target="#upload_mask">Upload</button>
               </div>
               <h2 class="panel-title">Masks</h2>
            </div>
            <div class="panel-body">
         <table class="table table-striped table-condensed">
            <tr>
               <td><b>Name</b></td>
               <td><b>MD5</b></td>
               <td></td>
            </tr>
            {% for mask in mask_list %}
            <tr>
               <td>{{ mask.name }}</td>
               <td>{{ mask.md5 }}</td>
               <td>
                     <form method="post">
                        {% csrf_token %}
                        <input type="hidden" name="action" value="remove"></input>
                        <input type="hidden" name="filetype" value="mask"></input>
                        <input type="hidden" name="filename" value="{{ mask.name }}"></input>
                        <button type="submit" class="btn btn-danger btn-xs confirm"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
                     </form>
               </td>
            </tr>
            {% endfor %}
         </table>
            </div>
         </div>

      </div>
      <div class="col-md-6">

         <div class="panel panel-primary">
            <div class="panel-heading">
               <div style="float: right;">
                  <button type="button" class="btn btn-xs btn-success" data-toggle="modal" data-target="#upload_wordlist">Upload</button>
               </div>
               <h2 class="panel-title">Wordlists</h2>
            </div>
            <div class="panel-body">

         <table class="table table-striped table-condensed">
            <tr>
               <td><b>Name</b></td>
               <td><b>Lines</b></td>
               <td><b>MD5</b></td>
               <td></td>
            </tr>
            {% for wordlist in wordlist_list %}
            <tr>
               <td>{{ wordlist.name }}</td>
               <td>{{ wordlist.lines }}</td>
               <td>{{ wordlist.md5 }}</td>
               <td>
                     <form method="post">
                        {% csrf_token %}
                        <input type="hidden" name="action" value="remove"></input>
                        <input type="hidden" name="filetype" value="wordlist"></input>
                        <input type="hidden" name="filename" value="{{ wordlist.name }}"></input>
                        <button type="submit" class="btn btn-danger btn-xs confirm"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
                     </form>
               </td>
            </tr>
            {% endfor %}
         </table>

            </div>
         </div>
      </div>
   </div>

   <!-- Modal -->
   <div class="modal fade" id="upload_rule" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
     <div class="modal-dialog modal-lg" role="document">
       <div class="modal-content">
         <div class="modal-header">
           <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
           <h4 class="modal-title" id="myModalLabel">Upload rule</h4>
         </div>

         <div class="modal-body">

            <form action="{% url "Hashcat:upload_rule" %}" enctype="multipart/form-data" method="post">
            {% csrf_token %}
            <label for="name">Name</label>
            <input type="text" class="form-control" id="name" name="name">
            </br>
            <input type="file" name="file" size="40">
            </br>
            <button type="submit" class="btn btn-primary" >Upload</button>
            </form>
         </div>

         <div class="modal-footer">
         </div>
       </div>
     </div>
   </div>

   <!-- Modal -->
   <div class="modal fade" id="upload_mask" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
     <div class="modal-dialog modal-lg" role="document">
       <div class="modal-content">
         <div class="modal-header">
           <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
           <h4 class="modal-title" id="myModalLabel">Upload mask</h4>
         </div>

         <div class="modal-body">

            <form action="{% url "Hashcat:upload_mask" %}" enctype="multipart/form-data" method="post">
            {% csrf_token %}
            <label for="name">Name</label>
            <input type="text" class="form-control" id="name" name="name">
            </br>
            <input type="file" name="file" size="40">
            </br>
            <button type="submit" class="btn btn-primary" >Upload</button>
            </form>
         </div>

         <div class="modal-footer">
         </div>
       </div>
     </div>
   </div>

   <!-- Modal -->
   <div class="modal fade" id="upload_wordlist" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
     <div class="modal-dialog modal-lg" role="document">
       <div class="modal-content">
         <div class="modal-header">
           <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
           <h4 class="modal-title" id="myModalLabel">Upload wordlist</h4>
         </div>

         <div class="modal-body">

            <form action="{% url "Hashcat:upload_wordlist" %}" enctype="multipart/form-data" method="post">
            {% csrf_token %}
            <label for="name">Name</label>
            <input type="text" class="form-control" id="name" name="name">
            </br>
            <input type="file" name="file" size="40">
            </br>
            <button type="submit" class="btn btn-primary" >Upload</button>
            </form>
         </div>

         <div class="modal-footer">
         </div>
       </div>
     </div>
   </div>

   <script type="text/javascript">
      $(function() {
          $('.confirm').click(function() {
              return window.confirm("Are you sure?");
          });
      });
   </script>



{% endblock %}

WebHashcat/Hashcat/templates/Hashcat/hashfile.html
{% extends "base.html" %}

{% block content %}

   <div class="row">
      <div class="col-md-6">
         <div class="panel panel-primary">
            <div class="panel-heading">

               <div style="float: right;">
                  <a href="{% url "Hashcat:export_cracked" hashfile.id %}" ><button type="submit" class="btn btn-success btn-xs confirm"><span class='glyphicon glyphicon-download-alt' ></span> Cracked</button></a>
                  <a href="{% url "Hashcat:export_uncracked" hashfile.id %}" ><button type="submit" class="btn btn-danger btn-xs confirm"><span class='glyphicon glyphicon-download-alt' ></span> Uncracked</button></a>
                  <a href="{% url "Hashcat:csv_masks" hashfile.id %}" ><button type="submit" class="btn btn-warning btn-xs confirm"><span class='glyphicon glyphicon-download-alt' ></span> Masks</button></a>
               </div>

               <h2 class="panel-title">{{ hashfile.name }}</h2>
            </div>
            <div class="panel-body">
               Hash type: {{ hash_type }}<br/>
               Lines: {{ lines }}<br/>
               Recovered: {{ recovered }}<br/>
            </div>
         </div>

         <table id="hashfile_table" class="table table-striped">
            <thead>
            <tr>
               {% if hashfile.username_included %}
               <td><b>Username</b></td>
               {% else %}
               <td><b>Hash</b></td>
               {% endif %}
               <td><b>Password</b></td>
            </tr>
            </thead>
         </table>
      </div>

      <script type="text/javascript">
   /* Formatting function for row details - modify as you need */

           $(document).ready( function () {
               // datatable
               var hashfile_table = $('#hashfile_table').DataTable({
                  "processing": true,
                  "serverSide": true,
                  "pageLength" : 25,
                  "columnDefs": [
                      { "width": "50%", "targets": 0},
                      { "width": "50%", "targets": 1},
                  ],
                  "ajax": {
                     "url": "{% url 'API:api_hashfile_cracked' hashfile.id %}",
                  },
                  "order": [[0, 'asc']]
               });
         });

      </script>



      <div class="col-md-6">
         <div class="panel panel-primary">
            <div class="panel-heading">
               <h2 class="panel-title">Top passwords</h2>
            </div>
            <div id="top_password_graph" class="panel-body"></div>
         </div>
         <div class="panel panel-primary">
            <div class="panel-heading">
               <h2 class="panel-title">Password lengths</h2>
            </div>
            <div id="pass_len_graph" class="panel-body"></div>
         </div>
         <div class="panel panel-primary">
            <div class="panel-heading">
               <h2 class="panel-title">Password charsets</h2>
            </div>
            <div id="top_pass_charset_graph" class="panel-body"></div>
         </div>

   <script type="text/javascript">
      var top_password_chart = new Highcharts.chart('top_password_graph', {
          chart: {
              type: 'bar',
              marginLeft: 140
          },
          title: {
              text: ''
          },
          xAxis: {
              categories: [],
              title: {
                  text: null
              }
          },
          yAxis: {
              min: 0,
              title: {
                  text: null,
                  align: 'high'
              },
              labels: {
                  overflow: 'justify'
              }
          },
          tooltip: {
              valueSuffix: ' hit'
          },
          plotOptions: {
              bar: {
                  dataLabels: {
                      enabled: false
                  }
              }
          },
          credits: {
              enabled: false
          },
          series: [{
              showInLegend: false,
              name: 'top passwords',
              data: [], //json_data['count_list'],
          }]
      });
      top_password_chart.showLoading();

      function update_top_password_chart() {
         top_password_chart.xAxis[0].setCategories(json_data['top_password_list']);
         top_password_chart.series[0].setData(json_data['count_list']);
         top_password_chart.hideLoading();
      }

      var json_data = [];
      $.getJSON('{% url "API:api_hashfile_top_password" hashfile.id 10 %}', function (data) {
         json_data = data; 

         update_top_password_chart();
      });

      var pass_len_chart = new Highcharts.chart('pass_len_graph', {
          chart: {
              type: 'column',
              marginLeft: 140
          },
          title: {
              text: ''
          },
          xAxis: {
              categories: [],
              title: {
                  text: null
              }
          },
          yAxis: {
              min: 0,
              title: {
                  text: null,
                  align: 'high'
              },
              labels: {
                  overflow: 'justify'
              }
          },
          tooltip: {
              valueSuffix: ' hit'
          },
          plotOptions: {
              bar: {
                  dataLabels: {
                      enabled: false
                  }
              }
          },
          credits: {
              enabled: false
          },
          series: [{
              showInLegend: false,
              name: 'password lengths',
              data: [],
          }]
      });
      pass_len_chart.showLoading();

      function update_pass_len_chart() {
         pass_len_chart.xAxis[0].setCategories(json_data['password_length_list']);
         pass_len_chart.series[0].setData(json_data['count_list']);
         pass_len_chart.hideLoading();
      }

      var json_data = [];
      $.getJSON('{% url "API:api_hashfile_top_password_len" hashfile.id 10 %}', function (data) {
         json_data = data; 

         update_pass_len_chart();
      });

      var top_pass_charset_chart = new Highcharts.chart('top_pass_charset_graph', {
          chart: {
              type: 'bar',
              marginLeft: 140
          },
          title: {
              text: ''
          },
          xAxis: {
              categories: [],
              title: {
                  text: null
              }
          },
          yAxis: {
              min: 0,
              title: {
                  text: null,
                  align: 'high'
              },
              labels: {
                  overflow: 'justify'
              }
          },
          tooltip: {
              valueSuffix: ' hit'
          },
          plotOptions: {
              bar: {
                  dataLabels: {
                      enabled: false
                  }
              }
          },
          credits: {
              enabled: false
          },
          series: [{
              showInLegend: false,
              name: 'password charsets',
              data: [],
          }]
      });
      top_pass_charset_chart.showLoading();

      function update_top_pass_charset_chart() {
         top_pass_charset_chart.xAxis[0].setCategories(json_data['password_charset_list']);
         top_pass_charset_chart.series[0].setData(json_data['count_list']);
         top_pass_charset_chart.hideLoading();
      }

      var json_data = [];
      $.getJSON('{% url "API:api_hashfile_top_password_charset" hashfile.id 10 %}', function (data) {
         json_data = data; 

         update_top_pass_charset_chart();
      });

   </script>

      </div>
   </div>
{% endblock %}